from enum import Enum


class ModuloEnum(str, Enum):
    ADMISIONES = "ADMISIONES"
    CARTERA = "CARTERA"
    CONTABILIDAD = "CONTABILIDAD"
    CONTRATOS_IPS = "CONTRATOS_IPS"
    FACTURACION = "FACTURACION"
    HOSPITALIZACION = "HOSPITALIZACION"
    INVENTARIOS = "INVENTARIOS"
    PAGOS = "PAGOS"
    TESORERIA = "TESORERIA"
    GENERALES_SEGURIDAD = "GENERALES_SEGURIDAD"
    CITAS_MEDICAS = "CITAS_MEDICAS"
    HISTORIAS_CLINICAS = "HISTORIAS_CLINICAS"
    ACTIVOS_FIJOS = "ACTIVOS_FIJOS"
    NOMINA = "NOMINA"
    INFORMACION_FINANCIERA_NIIF = "INFORMACION_FINANCIERA_NIIF"
    GESTION_GERENCIAL = "GESTION_GERENCIAL"
    WEB_CITAS_MEDICAS = "WEB_CITAS_MEDICAS"
    PROGRAMACION_DE_CIRUGIAS = "PROGRAMACION_DE_CIRUGIAS"
    OTROS = "OTROS"


class ImpactoEnum(str, Enum):
    ALTO = "alto"
    MEDIO = "medio"
    BAJO = "bajo"