export const API_BASE_URL =
  ((import.meta as any).env?.VITE_API_BASE_URL as string | undefined) ??
  "/api/v1";

export const MODULOS = [
  "ADMISIONES","CARTERA","CONTABILIDAD","CONTRATOS_IPS",
  "FACTURACION","HOSPITALIZACION","INVENTARIOS","PAGOS",
  "TESORERIA","GENERALES_SEGURIDAD","CITAS_MEDICAS",
  "HISTORIAS_CLINICAS","ACTIVOS_FIJOS","NOMINA",
  "INFORMACION_FINANCIERA_NIIF","GESTION_GERENCIAL",
  "WEB_CITAS_MEDICAS","PROGRAMACION_DE_CIRUGIAS","OTROS",
] as const;

export const MODULO_LABELS: Record<string,string> = {
  CONTRATOS_IPS: "CONTRATOS IPS",
  GENERALES_SEGURIDAD: "GENERALES & SEGURIDAD",
  CITAS_MEDICAS: "CITAS MEDICAS",
  HISTORIAS_CLINICAS: "HISTORIAS CLINICAS",
  ACTIVOS_FIJOS: "ACTIVOS FIJOS",
  WEB_CITAS_MEDICAS: "WEB CITAS MEDICAS",
  PROGRAMACION_DE_CIRUGIAS: "PROGRAMACION DE CIRUGIAS",
};

export const MODULOS_VALIDATOR = MODULOS as unknown as readonly string[];

// Fase 1 — Centralizados desde AccessRequestSections.tsx:74
export const AREAS_RESTABLECIMIENTO = [
  "ADMINISTRATIVO",
  "ADMISIONES",
  "ALMACEN",
  "AUDITORIA",
  "CARTERA",
  "COMUNICACIONES",
  "CONSULTA EXTERNA",
  "CONTABILIDAD",
  "ENFERMERIA",
  "FACTURACION",
  "FARMACIA",
  "FISIOTERAPIA",
  "INFRAESTRUCTURA",
  "INVESTIGACION",
  "LABORATORIO",
  "MEDICOS",
  "RADICACION",
  "SISTEMAS",
  "OTROS",
] as const;

export const CHART_COLORS = ["#0778ac", "#10b981", "#f59e0b", "#6366f1", "#ec4899", "#8b5cf6", "#14b8a6", "#f97316"] as const;
